# Manifiesto Kubernetes para el microservicio y Postgres
# Incluye: Secret, PVC, Deployment + Service para Postgres y Deployment + Service para la app

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  # Valores por defecto; en un entorno real cambie esto a valores seguros
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  POSTGRES_DB: mydb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          # Variables de entorno obtenidas del Secret
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          # Volumen para persistir los datos
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parte1-ms-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parte1-ms
  template:
    metadata:
      labels:
        app: parte1-ms
    spec:
      containers:
        - name: parte1-ms
          # Reemplace con su imagen (build & push antes de aplicar)
          image: andrmarce08/parte1-ms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          # Variables de entorno para la conexión a Postgres
          env:
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"
          # Cargar todas las claves del Secret como variables de entorno
          envFrom:
            - secretRef:
                name: postgres-secret
          # Health checks
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: parte1-ms-service
spec:
  selector:
    app: parte1-ms
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
