# Manifiesto Kubernetes para el microservicio y Postgres
# Incluye: Secret, PVC, Deployment + Service para Postgres y Deployment + Service para la app

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  # Credenciales para conectar a PostgreSQL en Helm
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mypassword
  POSTGRES_DB: mydb
  POSTGRES_HOST: mydb-postgresql.andresp1-dev.svc.cluster.local
  POSTGRES_PORT: "5432"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parte1-ms-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: parte1-ms
  template:
    metadata:
      labels:
        app: parte1-ms
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: parte1-ms
          image: DOCKER_IMAGE_URL
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: postgres-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 30
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: parte1-ms-service
spec:
  selector:
    app: parte1-ms
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP